### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John DoeUpdated",
  "email": "test@example.com",
  "address": "123 matara",
  "dateOfBirth": "2003-11-18"

}
###